name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Tạo file .env từ secret để dùng lúc build nếu cần (tùy bạn)
      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/chat-server:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/chat-server:latest

      - name: Deploy on EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Tạo file .env trên EC2 từ secret
            echo "${{ secrets.ENV_FILE }}" > ~/chat-service/.env
            
            # Kéo image mới từ Docker Hub
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/chat-server:latest
            
            # Dừng và xóa container cũ nếu có
            docker stop chat-server || true
            docker rm chat-server || true
            
            # Chạy container mới, mount file .env vào /app/.env trong container
            docker run -d -p 3000:3000 -p 8080:5000 --name chat-server -v ~/chat-service/.env:/app/.env ${{ secrets.DOCKERHUB_USERNAME }}/chat-server:latest
